// Generate the static interior pages and synchronize shared homepage navigation.
// Edit this file for shared chrome/interior content; homepage.html remains the home layout source.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = dirname(fileURLToPath(import.meta.url));
if (!existsSync(join(root, 'design-system.html'))) throw new Error('Preserve the visual guide as design-system.html before building the site entry point.');
let home = readFileSync(join(root, 'homepage.html'), 'utf8');
const icons = home.match(/<svg class="icon-library"[\s\S]*?<\/svg>/)[0];
const icon = name => `<svg class="icon" aria-hidden="true"><use href="#i-${name}"/></svg>`;
const versionAssets = html => html
  .replace(/href="((?:\.\.\/)?(?:tokens|components|homepage|site)\.css)(?:\?[^"]*)?"/g, 'href="$1?v=5"')
  .replace(/src="((?:\.\.\/)?(?:site|homepage)\.js)(?:\?[^"]*)?"/g, 'src="$1?v=5"');
const serviceRoutes = [
  ['skilled-nursing', 'Skilled nursing'],
  ['home-health-aide', 'Home health aide'],
  ['physical-therapy', 'Physical therapy'],
  ['occupational-therapy', 'Occupational therapy'],
  ['speech-therapy', 'Speech therapy'],
  ['medical-social-work', 'Medical social work']
];
const serviceSlugs = serviceRoutes.map(([slug]) => slug);
const routes = ['about', 'services', ...serviceSlugs, 'resources', 'careers', 'insurance-accepted', 'contact'];
const route = (slug, prefix = '../') => `${prefix}${slug === 'home' ? 'index.html' : `${slug}/index.html`}`;
const link = (slug, label, active, prefix) => `<a href="${route(slug, prefix)}"${active === slug ? ' aria-current="page"' : ''}>${label}</a>`;
function header(active, prefix = '../') {
  return `<div class="utility-bar"><div class="site-container utility-inner"><a class="utility-address" href="https://www.google.com/maps/search/?api=1&amp;query=13735+Victory+Blvd+Suite+18+Van+Nuys+CA+91401" target="_blank" rel="noopener noreferrer">${icon('pin')}13735 Victory Blvd, Suite 18, Van Nuys, CA 91401</a><div><a href="${route('careers', prefix)}">Join our team</a><span class="utility-divider" aria-hidden="true"></span><a href="tel:+18185325353">${icon('phone')}818-532-5353</a><span class="utility-divider" aria-hidden="true"></span><span class="utility-fax">FAX 818-584-8822</span></div></div></div>
<header class="site-header"><div class="site-container header-inner">
  <a class="brand" href="${route('home', prefix)}" aria-label="Orange Home Health home"${active === 'home' ? ' aria-current="page"' : ''}><img class="brand-logo" src="${prefix}assets/logo-transparent.png" width="1254" height="1254" alt="Orange Home Health Inc."></a>
  <nav class="desktop-nav" aria-label="Main navigation">
    ${link('home', 'Home', active, prefix)}${link('about', 'About us', active, prefix)}
    <details class="nav-dropdown${['services', ...serviceSlugs].includes(active) ? ' is-active' : ''}"><summary>Services</summary><div><a class="nav-overview" href="${route('services', prefix)}"${active === 'services' ? ' aria-current="page"' : ''}>All services →</a>${serviceRoutes.map(([slug, label]) => link(slug, label, active, prefix)).join('')}</div></details>
    ${link('careers', 'Careers', active, prefix)}${link('resources', 'Resources', active, prefix)}${link('insurance-accepted', 'Insurance accepted', active, prefix)}
  </nav>
  <a class="oh-btn header-cta" href="${route('contact', prefix)}"${active === 'contact' ? ' aria-current="page"' : ''}>Contact us ${icon('arrow')}</a>
  <details class="mobile-menu"><summary><span>Menu</span><span class="menu-lines" aria-hidden="true"></span></summary><nav aria-label="Mobile navigation">${link('home', 'Home', active, prefix)}${link('about', 'About us', active, prefix)}${link('services', 'All services', active, prefix)}${serviceRoutes.map(([slug, label]) => link(slug, label, active, prefix)).join('')}${link('careers', 'Careers', active, prefix)}${link('resources', 'Resources', active, prefix)}${link('insurance-accepted', 'Insurance accepted', active, prefix)}${link('contact', 'Contact us', active, prefix)}</nav></details>
</div></header>`;
}
function footer(prefix = '../') {
  return `<footer class="site-footer"><div class="site-container"><div class="footer-grid"><div class="footer-brand-column"><a class="brand" href="${route('home', prefix)}"><img class="brand-logo" src="${prefix}assets/logo-transparent.png" width="1254" height="1254" alt="Orange Home Health Inc."></a><p>Caring for you at home.</p><a class="footer-location" href="https://www.google.com/maps/search/?api=1&amp;query=13735+Victory+Blvd+Suite+18+Van+Nuys+CA+91401">${icon('pin')}<span>13735 Victory Blvd, Suite 18<br>Van Nuys, CA 91401</span></a></div>
<nav aria-label="Footer navigation"><h3>Explore Orange</h3><a href="${route('home', prefix)}">Home</a><a href="${route('about', prefix)}">About us</a><a href="${route('services', prefix)}">All services</a>${serviceRoutes.map(([slug, label]) => `<a href="${route(slug, prefix)}">${label}</a>`).join('')}<a href="${route('resources', prefix)}">Resources</a><a href="${route('careers', prefix)}">Careers</a><a href="${route('insurance-accepted', prefix)}">Insurance accepted</a><a href="${route('contact', prefix)}">Contact us</a></nav>
<div class="footer-contact"><h3>Let’s connect</h3><a href="tel:+18185325353">818-532-5353</a><a href="mailto:contact@orangehc.com">contact@orangehc.com</a><p>Fax: 818-584-8822</p><small>For general enquiries, please leave out private medical details.</small></div></div><div class="footer-bottom"><span>© 2026 Orange Home Health Inc.</span><span>Design preview · Illustrative imagery <a href="${prefix}design-system.html" target="_top">Design system ↗</a></span></div></div></footer>`;
}
const cta = (title = 'A little conversation.<br>A meaningful <em>beginning.</em>') => `<section class="contact-section"><div class="site-container contact-inner"><div><p class="eyebrow">FOR YOU. FOR SOMEONE YOU LOVE.</p><h2>${title}</h2><p>Let’s talk about care at home and the next step for your family.</p><div class="contact-actions"><a class="oh-btn" href="tel:+18185325353">${icon('phone')}Call 818-532-5353</a><a class="contact-link" href="../contact/index.html">Contact our team ${icon('arrow')}</a></div></div><div class="contact-emblem" aria-hidden="true"><svg viewBox="0 0 180 170"><path d="m18 81 72-61 72 61M35 74v75h110V74"/><path d="M90 130s-44-28-44-52c0-26 32-30 44-7 12-23 44-19 44 7 0 24-44 52-44 52Z"/></svg></div></div></section>`;
const crumbs = (title, service = false) => `<nav class="site-container breadcrumbs" aria-label="Breadcrumb"><a href="../index.html">Home</a><span aria-hidden="true">/</span>${service ? '<a href="../services/index.html">Our services</a><span aria-hidden="true">/</span>' : ''}<span aria-current="page">${title}</span></nav>`;
function photoHero({label, title, description, image, alt, variant = '', action = 'Talk about your care', href = '../contact/index.html'}) {
  return `<section class="inner-hero inner-hero--${variant}"><div class="site-container inner-hero-grid"><div class="inner-hero-copy"><p class="eyebrow">${label}</p><h1>${title}</h1><p>${description}</p><div class="hero-inline-actions"><a class="oh-btn" href="${href}">${action} ${icon('arrow')}</a><a class="text-link" href="tel:+18185325353">818-532-5353</a></div></div><figure><img class="inner-hero-photo" src="../assets/${image}" alt="${alt}" fetchpriority="high"></figure></div></section>`;
}
const plainHero = (label, title, description) => `<section class="plain-hero"><div class="site-container plain-hero-grid"><div><p class="eyebrow">${label}</p><h1>${title}</h1></div><p>${description}</p></div></section>`;
function sidebar(active) {
  return `<aside class="service-sidebar" aria-label="Explore our services"><h2>Care at home</h2><nav>${link('services', 'All services', active, '../')}${serviceRoutes.map(([slug, label]) => link(slug, label, active, '../')).join('')}</nav><a class="sidebar-call" href="tel:+18185325353">818-532-5353</a><small>A question is a good place to start.</small></aside>`;
}
const checklist = items => `<ul class="clinical-list">${items.map(item => `<li>${icon('check')}<span>${item}</span></li>`).join('')}</ul>`;
const faq = items => `<div class="detail-faq"><h2>Before you get started.</h2>${items.map(([question, answer]) => `<details class="oh-faq"><summary>${question}</summary><p>${answer}</p></details>`).join('')}</div>`;
const featured = () => `<div class="featured-services"><a class="photo-service" href="../skilled-nursing/index.html"><div class="service-photo"><img src="../assets/nursing.jpg" width="1024" height="683" alt="A nurse and an older woman talking at home" loading="lazy"><span class="service-tag">CLINICAL CARE, HUMAN CONNECTION</span></div><div class="service-content"><div><h3>Skilled nursing</h3><p>Nursing expertise with a personal touch.</p></div><span class="round-arrow" aria-hidden="true">↗</span></div></a><a class="photo-service" href="../home-health-aide/index.html"><div class="service-photo"><img src="../assets/home-health-aide.jpg" width="640" height="350" alt="A caregiver helping an older man walk at home" loading="lazy"><span class="service-tag">SUPPORT FOR THE EVERYDAY</span></div><div class="service-content"><div><h3>Home health aide</h3><p>Explore support with personal care at home.</p></div><span class="round-arrow" aria-hidden="true">↗</span></div></a></div>`;
const field = (id, label, {type = 'text', required = false, placeholder = ''} = {}) => `<div class="oh-field"><label for="${id}">${label}${required ? ' <span class="field-required" aria-hidden="true">*</span>' : ''}</label><input id="${id}" name="${id}" type="${type}" maxlength="150"${required ? ' required' : ''}${placeholder ? ` placeholder="${placeholder}"` : ''}></div>`;
const messageField = (id, label = 'Your message') => `<div class="oh-field"><label for="${id}">${label}</label><textarea id="${id}" name="${id}" rows="5" maxlength="2000" aria-describedby="${id}-hint"></textarea><span class="oh-hint" id="${id}-hint">Please leave out medical records, identity documents and other sensitive information.</span></div>`;
const formEnd = label => `<button class="oh-btn" type="submit" data-form-submit disabled>${label} ${icon('arrow')}</button><p class="form-outro">Preview only. To contact Orange now, call <a href="tel:+18185325353">818-532-5353</a>.</p><div class="oh-notice" role="status" tabindex="-1" hidden></div><noscript><p>The preview form needs JavaScript. You can still contact Orange by phone.</p></noscript></form>`;
const enquiryForm = (slug, title, intro = `Tell us what support you are looking for. Our team can explain assessment, availability and the next step.`) => `<section class="inner-section service-enquiry" id="contact-form"><div class="site-container form-layout"><div class="form-intro"><p class="eyebrow">ASK ABOUT ${title.toUpperCase()}</p><h2>Leave your details.<br>We’ll <em>talk.</em></h2><p>${intro}</p><p>Or call <a href="tel:+18185325353">818-532-5353</a>.</p></div><form class="site-form" data-preview-form autocomplete="off"><h2>Contact request</h2><p class="form-preview-note">Design preview. Use example details only. This form checks fields locally; nothing is sent or stored.</p><p class="form-required-note">Fields marked <span class="field-required">*</span> are required. All others are optional.</p>${field(`${slug}-name`, 'Full name', {required: true})}<div class="form-row">${field(`${slug}-email`, 'Email address', {type: 'email', required: true})}${field(`${slug}-phone`, 'Phone number', {type: 'tel', required: true})}</div>${messageField(`${slug}-message`, 'How can we help?')}${formEnd('Check request preview')}</div></section>`;
const supportServicePage = ({slug, title, label, heading, intro, image, alt, points}) => ({
  slug, title, description: `${title} services and contact information from Orange Home Health.`, service: true,
  body: photoHero({label, title: heading, description: intro, image, alt, variant: slug, action: 'Ask about this service', href: '#contact-form'}) +
  `<section class="inner-section"><div class="site-container detail-layout">${sidebar(slug)}<div class="detail-content"><p class="eyebrow">INDIVIDUAL SUPPORT AT HOME</p><h2>Start with your needs.<br>Build the plan <em>together.</em></h2><p>${intro}</p><h2 class="detail-heading">A conversation may include</h2>${checklist(points)}<div class="soft-callout"><h3>Assessment comes first.</h3><p>Contact Orange to discuss whether this service is appropriate and available for your individual situation.</p></div></div></div></section>` + enquiryForm(slug, title) + cta()
});
const pages = [
  {
    slug: 'skilled-nursing', title: 'Skilled Nursing', description: 'Explore nursing care at home, physician coordination and services offered by Orange Home Health.', service: true,
    body: photoHero({label: 'SKILLED NURSING AT HOME', title: 'Clinical expertise.<br><em>Human connection.</em>', description: 'Professional nursing support, delivered with care and understanding in the comfort of home.', image: 'nursing.jpg', alt: 'A nurse listening to an older woman at home', variant: 'nursing', action: 'Ask about this service', href: '#contact-form'}) +
    `<section class="inner-section"><div class="site-container detail-layout">${sidebar('skilled-nursing')}<div class="detail-content"><p class="eyebrow">CARE THAT FITS YOUR NEEDS</p><h2>A skilled team.<br>A personal <em>approach.</em></h2><p>Orange’s registered and licensed vocational nurses provide care and education at home, with attention to comfort and independence. Communication with your primary physician helps shape services around your individual needs.</p><h2 class="detail-heading">Nursing support may include</h2>${checklist(['Medication oversight, treatments and injections', 'Wound assessment and dressing changes', 'Assistance with ostomies and catheters', 'Blood draws and laboratory services', 'Intravenous infusion support', 'Nursing care before and after surgery', 'Restorative care and basic pulmonary physiotherapy', 'Diabetes education and guidance for patients and families', 'Coordination of referrals between facilities'])}<div class="soft-callout"><h3>Your care plan comes first.</h3><p>Ask our team which services are appropriate and available for your situation. Individual needs, assessment and coordination with your physician guide the next steps.</p></div>${faq([['How do I ask about nursing care?', 'Contact our team to discuss your needs, location and the information needed to begin an assessment.'], ['Will my physician be involved?', 'Orange’s nursing approach includes communication with the patient’s primary physician. Ask the team how that coordination would work for your care.']])}<a class="related-link" href="../home-health-aide/index.html"><span><small>ALSO EXPLORE</small><strong>Home health aide</strong></span>${icon('arrow')}</a></div></div></section>` + enquiryForm('skilled-nursing', 'Skilled nursing') + cta()
  },
  {
    slug: 'home-health-aide', title: 'Home Health Aide', description: 'Explore personal care support at home for you or someone you love.', service: true,
    body: photoHero({label: 'HOME HEALTH AIDE', title: 'A helping hand.<br><em>A familiar place.</em>', description: 'When everyday care calls for more support, start a conversation about help for you or someone you love.', image: 'home-health-aide.jpg', alt: 'A caregiver walking alongside an older man in his home', variant: 'aide', action: 'Ask about this service', href: '#contact-form'}) +
    `<section class="inner-section"><div class="site-container detail-layout">${sidebar('home-health-aide')}<div class="detail-content"><p class="eyebrow">SUPPORT FOR EVERYDAY LIFE</p><h2>You don’t have to figure<br>it out <em>alone.</em></h2><p>When personal care becomes difficult, or a family caregiver needs additional help, home health aide services can be part of the conversation. Orange helps families explore support in the home and the attention their loved one needs.</p><h2 class="detail-heading">Let’s talk about what would help.</h2>${checklist(['The personal care support you are looking for', 'Your loved one’s familiar routines and preferences', 'The help family caregivers are already providing', 'Your location, scheduling needs and language preference'])}<div class="soft-callout"><h3>Care that starts with listening.</h3><p>Tell our team what a typical day looks like. We’ll discuss needs, service availability and the next steps for an individual care plan.</p></div>${faq([['How is home health aide support arranged?', 'Start by contacting Orange. The team can explain assessment, care planning and current availability for your circumstances.'], ['Can you confirm a particular schedule?', 'Please ask our team directly about scheduling. A specific number of hours or round-the-clock availability is not confirmed by this design preview.']])}<a class="related-link" href="../skilled-nursing/index.html"><span><small>ALSO EXPLORE</small><strong>Skilled nursing</strong></span>${icon('arrow')}</a></div></div></section>` + enquiryForm('home-health-aide', 'Home health aide') + cta()
  },
  supportServicePage({slug: 'physical-therapy', title: 'Physical Therapy', label: 'PHYSICAL THERAPY AT HOME', heading: 'Move with support.<br><em>Progress at home.</em>', intro: 'Talk with Orange about physical therapy needs, assessment and available support in the home.', image: 'nursing.jpg', alt: 'A healthcare professional talking with an older woman at home', points: ['Your current movement and mobility needs', 'Safety, balance and daily routines at home', 'Physician coordination and assessment requirements', 'Your location and service availability']}),
  supportServicePage({slug: 'occupational-therapy', title: 'Occupational Therapy', label: 'OCCUPATIONAL THERAPY AT HOME', heading: 'Everyday activities.<br><em>Individual support.</em>', intro: 'Ask how occupational therapy may fit an individualized home health care plan and your daily routines.', image: 'home-health-aide.jpg', alt: 'A caregiver supporting an older adult at home', points: ['Activities that are difficult right now', 'Daily routines and independence goals', 'The home environment and practical needs', 'Assessment, coordination and availability']}),
  supportServicePage({slug: 'speech-therapy', title: 'Speech Therapy', label: 'SPEECH THERAPY AT HOME', heading: 'Communication matters.<br><em>Start by talking.</em>', intro: 'Contact Orange to discuss speech therapy services and the information needed for an assessment.', image: 'nursing.jpg', alt: 'A healthcare professional in conversation with an older woman', points: ['The support you are looking for', 'Current communication or swallowing concerns', 'Assessment and physician coordination', 'Your location and service availability']}),
  supportServicePage({slug: 'medical-social-work', title: 'Medical Social Work', label: 'MEDICAL SOCIAL WORK', heading: 'Questions become clearer.<br><em>Support feels closer.</em>', intro: 'Explore medical social work support for the care questions and resources your family is navigating.', image: 'home-health-aide.jpg', alt: 'A caregiver and older adult walking together at home', points: ['Questions about the care situation', 'Family and caregiver support needs', 'Resources you are trying to understand', 'Next steps within an individual care plan']}),
  {
    slug: 'services', title: 'Our Services', description: 'Skilled nursing, home health aide, therapy and social work services from Orange Home Health.',
    body: `<section class="services-page-hero" data-services-video aria-labelledby="services-title"><video autoplay muted loop playsinline preload="metadata" poster="../assets/services-video-poster.png" aria-label="Orange Home Health introduction"><source src="../assets/services-introduction.mp4" type="video/mp4">Your browser does not support this video.</video><div class="services-page-shade" aria-hidden="true"></div><div class="site-container services-page-hero-inner"><div class="services-page-copy"><p class="eyebrow">CARE, BUILT AROUND YOU</p><h1 id="services-title">The support you need.<br>The home you <em>love.</em></h1><p>Explore care at home, from nursing and personal support to therapy and medical social work. Start with your needs. We’ll talk about the next step.</p><button class="services-video-play" type="button" data-services-video-play><span aria-hidden="true">▶</span>Watch video</button></div></div></section>` +
    `<section class="inner-section service-catalog"><div class="site-container">${featured()}<div id="therapy" class="catalog-grid">${[
      ['physical-therapy', 'move', 'Physical therapy', 'Discuss physical therapy needs, assessment and available services with our team.'],
      ['occupational-therapy', 'care', 'Occupational therapy', 'Ask about occupational therapy as part of an individualized home health care plan.'],
      ['speech-therapy', 'chat', 'Speech therapy', 'Talk with us about speech therapy services and the next steps for assessment.'],
      ['medical-social-work', 'people', 'Medical social work', 'Explore medical social work support and the questions your family would like help navigating.']
    ].map(([id, symbol, title, description]) => `<article class="catalog-card" id="${id}">${icon(symbol)}<h2>${title}</h2><p>${description}</p><a class="text-link" href="../${id}/index.html">View service ${icon('arrow')}</a></article>`).join('')}</div></div></section>
    <section class="inner-section care-start" id="how-care-works"><div class="site-container"><div><p class="eyebrow">THOUGHTFUL FROM THE START</p><h2>One person.<br>One individual<br><em>care plan.</em></h2><p>Our services begin with an assessment and a plan shaped around your care requirements.</p><a class="text-link" href="../contact/index.html">Talk to Orange ${icon('arrow')}</a></div><ol class="care-start-list"><li><span>01</span><div><h3>Begin with your questions</h3><p>Discuss the support you need, where you live and how we can reach you.</p></div></li><li><span>02</span><div><h3>Understand the assessment</h3><p>Learn what information is needed and how your care requirements are reviewed.</p></div></li><li><span>03</span><div><h3>Plan the next step</h3><p>Talk through an individualized service plan and confirm availability with the team.</p></div></li></ol></div></section>
    <section class="inner-section"><div class="site-container mission-grid"><div><p class="eyebrow">PRACTICAL QUESTIONS MATTER</p><h2>Your area.<br>Your questions.</h2></div><div class="mission-copy"><p>Our office is in Van Nuys. Contact Orange to confirm home-visit availability at your address and ask about payment or coverage for your situation.</p><a class="oh-btn oh-btn--secondary" href="../contact/index.html">Check with our team ${icon('arrow')}</a></div></div></section>` + cta()
  },
  {
    slug: 'about', title: 'About Us', description: 'Learn about Orange Home Health’s person-centered approach to care in the Los Angeles community.',
    body: photoHero({label: 'ABOUT ORANGE HOME HEALTH', title: 'People first.<br><em>Home, always.</em>', description: 'Healthcare is personal. So is home. Our approach brings the two together with thoughtful, individualized support.', image: 'hero-poster.jpg', alt: 'An older woman and caregiver talking in a sunlit living room', variant: 'about', action: 'Explore our services', href: '../services/index.html'}) +
    `<section class="inner-section"><div class="site-container mission-grid"><div><p class="eyebrow">OUR PURPOSE</p><h2>Care for a person.<br>Support for<br><em>a family.</em></h2></div><div class="mission-copy"><p class="mission-statement">Our priority is the people in our care and the families beside them.</p><p>Orange Home Health provides personalized care at home in the Los Angeles community. We bring professional knowledge, attentive visits and respect for individual needs to the care-planning process.</p><p>We also help coordinate medical equipment and appliances. Ask our team how this may fit into your care needs.</p></div></div></section>
    <section class="inner-section values-section"><div class="site-container"><div class="section-heading"><div><p class="eyebrow">WHAT GUIDES OUR APPROACH</p><h2>Professional care.<br><em>Human values.</em></h2></div></div><div class="values-grid"><article class="value-item">${icon('heart')}<h3>The person comes first</h3><p>Individual needs and care requirements guide the plan.</p></article><article class="value-item">${icon('home')}<h3>Respect for home</h3><p>Care belongs in the context of your familiar surroundings and daily life.</p></article><article class="value-item">${icon('people')}<h3>Connection matters</h3><p>We welcome questions and the diverse languages of our community.</p></article></div></div></section>
    ${home.match(/<section class="language-section[\s\S]*?<\/section>/)[0].replace(/href="(?:#contact|contact\/index.html)"/g, 'href="../contact/index.html"')}` + cta()
  },
  {
    slug: 'resources', title: 'Resources', description: 'Explore the organizations and information resources listed by Orange Home Health.',
    body: plainHero('INFORMATION, WITH A LITTLE CLARITY', 'A place to learn.<br>A place to <em>begin.</em>', 'Find the organizations and information resources shared by Orange, along with a few practical questions for your first conversation.') +
    `<section class="inner-section"><div class="site-container resources-layout"><div class="resource-intro"><p class="eyebrow">FURTHER READING</p><h2>Helpful places<br>to explore.</h2><p>These links take you to independent organizations outside the Orange website.</p></div><div>${[
      ['ANA', 'American Nurses Association', 'Nursing profession and professional resources.', 'nursingworld.org', 'https://www.nursingworld.org/'],
      ['Care', 'Caregiving.com', 'A community and resources for family caregivers.', 'caregiving.com', 'https://www.caregiving.com/'],
      ['W', 'WebMD', 'An external health-information resource listed by Orange.', 'webmd.com', 'https://www.webmd.com/'],
      ['Mayo', 'Mayo Clinic', 'Information from Mayo Clinic’s official website.', 'mayoclinic.org', 'https://www.mayoclinic.org/'],
      ['HCAOA', 'Home Care Association of America', 'The home care association’s official website.', 'hcaoa.org', 'https://www.hcaoa.org/']
    ].map(([mark, name, description, domain, url]) => `<a class="resource-item" href="${url}" target="_blank" rel="noopener noreferrer"><span class="resource-monogram" aria-hidden="true">${mark}</span><div><h2>${name}</h2><p>${description}</p><small>${domain} · Opens a new tab</small></div>${icon('arrow')}</a>`).join('')}<p class="resource-note">General information does not replace advice from your own healthcare professional. These links do not imply a partnership or endorsement by the linked organizations.</p></div></div></section>
    <section class="inner-section care-start"><div class="site-container" style="display:block"><p class="eyebrow">BEFORE YOU CALL</p><h2>You can start with<br><em>these questions.</em></h2><div class="question-grid"><article><h3>Which services fit my needs?</h3><p>Ask what an assessment involves and which services may be available.</p></article><article><h3>Is my address in your area?</h3><p>Share your location with the team to confirm home-visit availability.</p></article><article><h3>What should I know about payment?</h3><p>Ask about your circumstances, coverage questions and the next steps.</p></article></div></div></section><section class="inner-section"><div class="site-container"><a class="text-link" href="../homepage.html#faq">More common questions ${icon('arrow')}</a></div></section>` + cta('Have a question?<br>Let’s <em>talk it through.</em>')
  },
  {
    slug: 'careers', title: 'Careers', description: 'Introduce yourself to Orange Home Health and ask about opportunities to join the care team.',
    body: photoHero({label: 'CAREERS AT ORANGE', title: 'Bring your care.<br><em>Make it personal.</em>', description: 'Interested in being part of a compassionate home health team? Tell us about yourself and the role you’re looking for.', image: 'nursing.jpg', alt: 'A healthcare professional sharing a warm conversation at home', variant: 'careers', action: 'Introduce yourself', href: '#application'}) +
    `<section class="inner-section" id="application"><div class="site-container form-layout"><div class="form-intro"><p class="eyebrow">A MEANINGFUL INTRODUCTION</p><h2>Care starts<br>with <em>people.</em></h2><p>Use this application layout to introduce your experience and the kind of position that interests you.</p><p>For current vacancies, requirements and hiring details, contact Orange directly. This page does not advertise a confirmed open position.</p><div class="soft-callout"><h3>Have a question first?</h3><p>Call <a href="tel:+18185325353">818-532-5353</a> to ask about joining the team.</p></div></div><form class="site-form" data-preview-form autocomplete="off"><h2>Introduce yourself</h2><p class="form-preview-note">Design preview. Use example details only. This form checks fields locally; it does not send an application.</p><p class="form-required-note">Fields marked <span class="field-required">*</span> are required. All others are optional.</p><div class="form-row">${field('first-name', 'First name', {required: true})}${field('last-name', 'Last name', {required: true})}</div>${field('career-email', 'Email address', {type: 'email', required: true})}<div class="form-row">${field('career-phone', 'Phone number', {type: 'tel', required: true})}${field('cell-number', 'Alternative / cell number', {type: 'tel'})}</div>${field('position', 'Position of interest', {required: true, placeholder: 'Tell us the role you are interested in'})}${messageField('career-message', 'A little about you')}${formEnd('Check application preview')}</div></section>`
  },
  {
    slug: 'insurance-accepted', title: 'Insurance Accepted', description: 'Contact Orange Home Health to ask about insurance coverage and payment for home health services.',
    body: plainHero('INSURANCE & PAYMENT', 'Let’s check your<br><em>coverage.</em>', 'Insurance acceptance can depend on the service, your plan and authorization. Share the name of your plan so our team can help you understand the next step.') +
    `<section class="inner-section"><div class="site-container form-layout"><div class="form-intro"><p class="eyebrow">CONFIRM BEFORE CARE BEGINS</p><h2>Plans can change.<br>Please <em>ask us.</em></h2><p>Accepted plans and benefits can change. Contact Orange before care begins so the team can confirm current information for your plan and situation.</p><div class="contact-methods"><div class="contact-method">${icon('phone')}<div><small>CALL TO CHECK COVERAGE</small><a href="tel:+18185325353">818-532-5353</a><p>Fax: 818-584-8822</p></div></div><div class="contact-method">${icon('chat')}<div><small>EMAIL</small><a href="mailto:contact@orangehc.com">contact@orangehc.com</a></div></div></div></div><form class="site-form" data-preview-form autocomplete="off"><h2>Ask about your plan</h2><p class="form-preview-note">Design preview. Use example details only. This form checks fields locally; nothing is sent or stored.</p><p class="form-required-note">Fields marked <span class="field-required">*</span> are required. All others are optional.</p>${field('insurance-name', 'Full name', {required: true})}<div class="form-row">${field('insurance-email', 'Email address', {type: 'email', required: true})}${field('insurance-phone', 'Phone number', {type: 'tel', required: true})}</div>${field('insurance-provider', 'Insurance company or plan name')}${messageField('insurance-message', 'Your coverage question')}${formEnd('Check coverage request')}</div></section>`
  },
  {
    slug: 'contact', title: 'Contact Us', description: 'Call Orange Home Health at 818-532-5353 or find the office and contact details in Van Nuys.',
    body: plainHero('LET’S TALK ABOUT CARE', 'A question is a<br><em>good beginning.</em>', 'For yourself or someone you love, reach out to discuss care at home. We can help you understand the next step.') +
    `<section class="inner-section"><div class="site-container form-layout"><div><div class="contact-methods"><div class="contact-method">${icon('phone')}<div><small>GIVE US A CALL</small><a href="tel:+18185325353">818-532-5353</a><p>Fax: 818-584-8822</p></div></div><div class="contact-method">${icon('chat')}<div><small>SEND A GENERAL ENQUIRY</small><a href="mailto:contact@orangehc.com">contact@orangehc.com</a><p>Please leave out private medical information.</p></div></div></div><div class="office-card"><p class="eyebrow">OUR OFFICE</p><h3>Van Nuys, Los Angeles</h3><p>13735 Victory Blvd, Suite 18<br>Van Nuys, CA 91401</p><a class="text-link" href="https://www.google.com/maps/search/?api=1&amp;query=13735+Victory+Blvd+Suite+18+Van+Nuys+CA+91401" target="_blank" rel="noopener noreferrer">Open in Google Maps ${icon('arrow')}</a><small>Opens a new tab. Please confirm home-visit coverage with our team; the office address does not define the service area.</small></div><div class="contact-questions"><h3>Not sure where to start?</h3><a class="text-link" href="../services/index.html">Explore our services ${icon('arrow')}</a></div></div><form class="site-form" data-preview-form autocomplete="off"><h2>Send a general enquiry</h2><p class="form-preview-note">Design preview. Use example details only. This form checks fields locally; nothing is sent or stored.</p><p class="form-required-note">Fields marked <span class="field-required">*</span> are required. All others are optional.</p>${field('full-name', 'Full name', {required: true})}<div class="form-row">${field('contact-email', 'Email address', {type: 'email', required: true})}${field('contact-phone', 'Phone number', {type: 'tel', required: true})}</div>${field('address', 'Address or city')}${messageField('contact-message')}${formEnd('Check enquiry preview')}</div></section>`
  }
];
for (const page of pages) {
  const directory = join(root, page.slug);
  mkdirSync(directory, {recursive: true});
  writeFileSync(join(directory, 'index.html'), versionAssets(`<!doctype html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><meta name="description" content="${page.description}"><meta name="theme-color" content="#18354A"><title>${page.title} | Orange Home Health</title><link rel="icon" href="../assets/logo-mark.svg" type="image/svg+xml"><link rel="preload" href="../assets/manrope-latin.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="../tokens.css"><link rel="stylesheet" href="../components.css"><link rel="stylesheet" href="../homepage.css"><link rel="stylesheet" href="../site.css"><script src="../site.js" defer></script></head>
<body><a class="oh-skip" href="#main">Skip to content</a>${icons}${header(page.slug)}<main id="main">${crumbs(page.title, page.service)}${page.body}</main>${footer()}</body></html>\n`));
}
home = home.replace(/<div class="utility-bar">[\s\S]*?<\/header>/, header('home', ''));
home = home.replace(/<footer class="site-footer">[\s\S]*?<\/footer>/, footer(''));
for (const slug of routes) home = home.replaceAll(`https://orangehomehealthinc.com/${slug}/`, `${slug}/index.html`);
home = home.replace('href="#contact">Find care for your family', 'href="contact/index.html">Find care for your family');
home = home.replace('href="#contact">Talk with our team', 'href="contact/index.html">Talk with our team');
for (const [symbol, id] of [['move', 'physical-therapy'], ['care', 'occupational-therapy'], ['chat', 'speech-therapy'], ['people', 'medical-social-work']]) {
  home = home.replaceAll(`href="services/index.html#${id}"`, `href="${id}/index.html"`);
  home = home.replace(`href="services/index.html"><svg class="icon" aria-hidden="true"><use href="#i-${symbol}"`, `href="${id}/index.html"><svg class="icon" aria-hidden="true"><use href="#i-${symbol}"`);
}
if (!/href="site\.css(?:\?[^"]*)?"/.test(home)) home = home.replace('<script src="homepage.js"', '<link rel="stylesheet" href="site.css">\n  <script src="site.js" defer></script>\n  <script src="homepage.js"');
home = versionAssets(home);
writeFileSync(join(root, 'homepage.html'), home);
writeFileSync(join(root, 'index.html'), home);
console.log(`Built ${pages.length} interior pages and synchronized homepage navigation. Website now has ${pages.length + 1} public-page designs.`);
