import { readFileSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
const root = dirname(fileURLToPath(import.meta.url));
const serviceSlugs = ['skilled-nursing', 'home-health-aide', 'physical-therapy', 'occupational-therapy', 'speech-therapy', 'medical-social-work'];
const servicePageFiles = serviceSlugs.map(slug => `${slug}/index.html`);
const pageFiles = ['index.html', 'homepage.html', ...['about', 'services', ...serviceSlugs, 'resources', 'careers', 'coverage-area', 'insurance-accepted', 'contact'].map(slug => `${slug}/index.html`)];
const getIds = html => [...html.matchAll(/\bid="([^"]+)"/g)].map(match => match[1]);
for (const file of pageFiles) {
  const pagePath = resolve(root, file);
  const html = readFileSync(pagePath, 'utf8');
  const ids = getIds(html);
  assert.equal(ids.length, new Set(ids).size, `${file}: duplicate IDs`);
  assert.equal((html.match(/<h1\b/g) || []).length, 1, `${file}: exactly one h1`);
  const footer = html.match(/<footer class="site-footer">[\s\S]*?<\/footer>/)?.[0];
  assert.ok(footer, `${file}: missing shared footer`);
  const footerNavigation = [...footer.matchAll(/<nav\b[\s\S]*?<\/nav>/g)].map(match => match[0]);
  assert.equal(footerNavigation.length, 2, `${file}: footer must have two navigation columns`);
  assert.equal(footerNavigation.reduce((total, nav) => total + (nav.match(/<a\b/g) || []).length, 0), 14, `${file}: retain all fourteen footer destinations`);
  for (const network of ['Instagram', 'Facebook', 'YouTube', 'Yelp', 'Google']) assert.match(footer, new RegExp(`>${network}<`), `${file}: footer missing ${network}`);
  for (const network of ['instagram', 'facebook', 'youtube', 'yelp', 'google']) assert.match(footer, new RegExp(`assets/social-${network}\\.svg`), `${file}: footer missing official ${network} icon`);
  const header = html.match(/<header class="site-header">[\s\S]*?<\/header>/)?.[0];
  assert.ok(header, `${file}: missing shared header`);
  for (const label of ['Home', 'About us', 'Services', 'Careers', 'Resources', 'Coverage area', 'Insurance accepted', 'Contact us']) assert.ok(header.includes(label), `${file}: header missing ${label}`);
  for (const [, ref] of html.matchAll(/(?:src|href|poster)="([^"]+)"/g)) {
    if (/^(https?:|tel:|mailto:)/.test(ref)) continue;
    const [urlPath, fragment] = ref.split('#');
    const path = urlPath.split('?')[0];
    const target = path ? resolve(dirname(pagePath), path) : pagePath;
    assert.ok(existsSync(target), `${file}: missing local target ${ref}`);
    if (fragment) assert.ok(getIds(readFileSync(target, 'utf8')).includes(fragment), `${file}: missing anchor ${ref}`);
  }
  for (const [image] of html.matchAll(/<img\b[^>]*>/g)) assert.match(image, /\balt="[^"]*"/, `${file}: image needs alt text`);
  assert.match(html, /name="robots" content="noindex"/, `${file}: noindex required`);
  assert.match(html, /src="(?:\.\.\/)?site.js\?v=23"/, `${file}: shared interaction script missing`);
  assert.match(html, /(?:site\.css|homepage\.css)\?v=23/, `${file}: versioned local styles are required`);
  assert.match(html, /site\.js\?v=23/, `${file}: versioned shared script is required`);
  assert.match(html, /href="#i-fax"/, `${file}: fax icon missing`);
  assert.match(html, /aria-label="Fax: 818-584-8822"/, `${file}: accessible fax number missing`);
  assert.ok(!html.includes('FAX 818-584-8822'), `${file}: visible FAX text must be replaced by the icon`);
  assert.match(html, /13735 Victory Blvd, Suite 18, Van Nuys, CA 91401/, `${file}: utility address missing`);
  assert.ok(!html.includes('href="https://orangehomehealthinc.com/'), `${file}: internal links must stay in the new design`);
  for (const [, id] of html.matchAll(/<(?:input|textarea)\b[^>]*\bid="([^"]+)"/g)) assert.ok(html.includes(`for="${id}"`), `${file}: missing field label ${id}`);
  if (['contact/index.html', 'careers/index.html', 'insurance-accepted/index.html', ...servicePageFiles].includes(file)) {
    for (const type of ['email', 'tel']) assert.match(html, new RegExp(`<input[^>]*type="${type}"[^>]* required`), `${file}: email and primary phone must be required`);
    assert.match(html, /Fields marked[\s\S]*?are required\. All others are optional\./, `${file}: required-field legend missing`);
    assert.ok(!/<label[^>]*>[^<]*\((?:optional|required)\)/.test(html), `${file}: use compact required markers`);
  }
  if (servicePageFiles.includes(file)) assert.match(html, /<form class="site-form" data-preview-form/, `${file}: service enquiry form missing`);
}
const html = readFileSync(resolve(root, 'homepage.html'), 'utf8');
assert.equal(html, readFileSync(resolve(root, 'index.html'), 'utf8'), 'Home alias must match the website entry point');
assert.match(html, /<dialog\b[^>]*aria-labelledby="intro-title"/, 'Introduction must have a named native dialog');
assert.ok(!html.includes('play-circle'), 'Remove the circular play control');
assert.match(readFileSync(resolve(root, 'homepage.js'), 'utf8'), /const HERO_VIDEO = 'assets\/hero-introduction\.mp4'/, 'Homepage hero must use its original video');
assert.match(readFileSync(resolve(root, 'homepage.js'), 'utf8'), /const INTRO_VIDEO = 'assets\/hero-introduction\.mp4'/, 'Hero watch button must open the original video');
assert.match(readFileSync(resolve(root, 'skilled-nursing/index.html'), 'utf8'), /<source src="\.\.\/assets\/skilled-nursing\.mp4" type="video\/mp4">/, 'Skilled Nursing hero video missing');
assert.match(readFileSync(resolve(root, 'skilled-nursing/index.html'), 'utf8'), /Watch the Skilled Nursing video\./, 'Skilled Nursing video title missing');
assert.match(readFileSync(resolve(root, 'speech-therapy/index.html'), 'utf8'), /<source src="\.\.\/assets\/speech-therapy\.mp4" type="video\/mp4">/, 'Speech Therapy hero video missing');
assert.match(readFileSync(resolve(root, 'speech-therapy/index.html'), 'utf8'), /class="cinema-hero service-cinema-hero"/, 'Speech Therapy needs a full-width video hero');
assert.match(readFileSync(resolve(root, 'speech-therapy/index.html'), 'utf8'), /data-open-video="service-video-dialog"/, 'Speech Therapy needs a full-video button');
assert.match(readFileSync(resolve(root, 'speech-therapy/index.html'), 'utf8'), /data-video-dialog/, 'Speech Therapy full-video dialog missing');
assert.match(readFileSync(resolve(root, 'site.js'), 'utf8'), /\[data-video-dialog\]/, 'Service video dialog behavior missing');
const occupationalHtml = readFileSync(resolve(root, 'occupational-therapy/index.html'), 'utf8');
assert.match(occupationalHtml, /<source src="\.\.\/assets\/occupational-therapy\.mp4" type="video\/mp4">/, 'Occupational Therapy hero video missing');
assert.match(occupationalHtml, /Watch the Occupational Therapy video\./, 'Occupational Therapy video title missing');
assert.ok(!occupationalHtml.includes('Orange Home Health · Speech Therapy'), 'Occupational Therapy must not use the Speech Therapy label');
assert.match(html, /Watch video/, 'Hero needs a clear video button');
assert.match(readFileSync(resolve(root, 'services/index.html'), 'utf8'), /<source src="\.\.\/assets\/services-introduction\.mp4" type="video\/mp4">/, 'Services page video missing');
assert.match(readFileSync(resolve(root, 'services/index.html'), 'utf8'), /data-services-video-play/, 'Services page needs a clear video button');
assert.match(readFileSync(resolve(root, 'services/index.html'), 'utf8'), /class="services-page-hero"/, 'Services heading and video must share one hero section');
assert.match(readFileSync(resolve(root, 'services/index.html'), 'utf8'), /<video autoplay muted loop playsinline/, 'Services hero video must autoplay silently without visible controls');
assert.match(html, /HOME HEALTH CARE IN SOUTHERN CALIFORNIA/, 'Homepage service area label must name Southern California');
const aboutHtml = readFileSync(resolve(root, 'about/index.html'), 'utf8');
assert.match(aboutHtml, /class="about-purpose-panel"/, 'About page purpose panel missing');
assert.equal((aboutHtml.match(/class="value-item"/g) || []).length, 3, 'About page needs three value cards');
assert.match(aboutHtml, /class="inner-section social-section"/, 'About page social section missing');
assert.equal((aboutHtml.match(/class="social-card"/g) || []).length, 5, 'About page needs five social links');
assert.equal((aboutHtml.match(/class="credential-card"/g) || []).length, 4, 'About page needs four credential cards');
assert.equal((html.match(/class="credential-card"/g) || []).length, 4, 'Homepage needs four credential cards');
assert.equal((aboutHtml.match(/class="review-card"/g) || []).length, 13, 'About page needs all written Google and Yelp review cards');
assert.equal((html.match(/class="review-card"/g) || []).length, 13, 'Homepage needs all written Google and Yelp review cards');
const coverageHtml = readFileSync(resolve(root, 'coverage-area/index.html'), 'utf8');
for (const county of ['Los Angeles County', 'Orange County', 'Riverside County', 'San Bernardino County', 'Ventura County', 'Kern County']) assert.match(coverageHtml, new RegExp(county), `Coverage page missing ${county}`);
for (const county of ['San Diego', 'Imperial', 'Santa Barbara']) assert.match(coverageHtml, new RegExp(`${county} County`), `Coverage page missing ${county} County`);
assert.match(coverageHtml, /<strong>9<\/strong><span>counties served<\/span>/, 'Coverage county count must include the new counties');
assert.ok(!coverageHtml.includes('image.png'), 'Coverage page must not include the pasted image placeholder');
assert.match(coverageHtml, /id="our-commitment"/, 'Coverage page must expose the Our Commitment section');
assert.match(coverageHtml, /<strong>88<\/strong><span>communities listed/, 'Coverage page community count must stay in sync');
assert.match(coverageHtml, /17 COMMUNITIES<\/p><h3>San Diego County<\/h3>/, 'San Diego County must list all 17 cities');
assert.match(coverageHtml, /7 COMMUNITIES<\/p><h3>Imperial County<\/h3>/, 'Imperial County must list all 7 cities');
assert.match(coverageHtml, /15 COMMUNITIES<\/p><h3>Santa Barbara County<\/h3>/, 'Santa Barbara County must list all 15 communities');
assert.match(coverageHtml, /San Diego \(County seat\)/, 'San Diego county seat missing');
const insuranceHtml = readFileSync(resolve(root, 'insurance-accepted/index.html'), 'utf8');
assert.match(insuranceHtml, /We are in-network with the following <em>insurance providers\.<\/em>/, 'Insurance network heading missing');
assert.equal((insuranceHtml.match(/class="insurance-logo-card"/g) || []).length, 4, 'Insurance page needs four confirmed provider logos');
for (const provider of ['Anthem', 'Blue Shield of California', 'UnitedHealthcare', 'Seoul Medical Group']) assert.match(insuranceHtml, new RegExp(`<h3>${provider}<\\/h3>`), `Insurance page missing ${provider}`);
const siteJs = readFileSync(resolve(root, 'site.js'), 'utf8');
const siteCss = readFileSync(resolve(root, 'site.css'), 'utf8');
const homepageCss = readFileSync(resolve(root, 'homepage.css'), 'utf8');
assert.match(siteJs, /IntersectionObserver/, 'Shared scroll reveal behavior is missing');
assert.match(siteCss, /\.reveal-on-scroll/, 'Shared scroll reveal styles are missing');
assert.match(siteCss, /@starting-style/, 'Navigation opening transition is missing');
assert.match(homepageCss, /\.oh-faq::details-content/, 'FAQ opening transition is missing');
const tokens = JSON.parse(readFileSync(resolve(root, 'figma-tokens.json'), 'utf8'));
const css = readFileSync(resolve(root, 'tokens.css'), 'utf8');
for (const key of ['Brand/Orange', 'Brand/Blue', 'Ink/Navy', 'Ink/Body', 'Ink/Muted', 'State/Focus']) assert.ok(css.includes(tokens.color[key]), `${key} differs from the foundation`);
assert.equal(tokens.motion.IntroSceneSeconds * 3, tokens.motion.IntroTotalSeconds);
assert.ok(existsSync(resolve(root, 'assets/speech-therapy.mp4')), 'Missing Speech Therapy video');
assert.ok(existsSync(resolve(root, 'assets/skilled-nursing.mp4')), 'Missing Skilled Nursing video');
for (const file of ['START-HERE.txt', 'DEVELOPER-HANDOFF.md', 'FIGMA-HANDOFF.md', 'figma-foundations.svg', 'assets/logo-client-reference.png', 'assets/logo-transparent.png', 'assets/logo-full.svg', 'assets/logo-reconstruction.svg', 'assets/OFL.txt', 'assets/hero-introduction.mp4', 'assets/services-introduction.mp4', 'assets/services-video-poster.png']) assert.ok(existsSync(resolve(root, file)), `Missing handoff file: ${file}`);
for (const network of ['instagram', 'facebook', 'youtube', 'yelp', 'google']) assert.ok(existsSync(resolve(root, `assets/social-${network}.svg`)), `Missing social icon: ${network}`);
for (const insurer of ['anthem', 'blue-shield-california', 'united-healthcare', 'seoul-medical-group']) assert.ok(existsSync(resolve(root, `assets/insurance-${insurer}.png`)), `Missing insurance logo: ${insurer}`);
for (const credential of ['achc', 'medicare', 'cms', 'sba-wosb']) assert.ok(existsSync(resolve(root, `assets/credential-${credential}.png`)), `Missing credential logo: ${credential}`);
for (const file of pageFiles) assert.match(readFileSync(resolve(root, file), 'utf8'), /assets\/logo-transparent\.png/, `${file}: transparent PNG logo missing`);
console.log('PASS: offline-ready 14-page website + home alias; local links, assets, forms, animations, tokens and developer handoff files.');
